### ISSUE TITLE
Unexpected exit with no traceback in eye_process.py and other OpenCV examples

### ISSUE THREAD

**Issue by villar10** [ParisNeo/FaceAnalyzer#11]
In a clean environment with Python 3.9.13 installing only needed dependencies, eye_process.py and many other OpenCV examples either return empty arrays from Face.py or silently exit.

Root cause is the use of 'astype(np.[datatype])' throughout Face.py . Using native data types instead of the numpy prefixed data types where possible fixes this issue. I also found it works if the data type is changed to a data type explicitly listed out in the article below, such as 'np.intc' as opposed to 'np.int'. Not sure the reason why this is breaking it, but it may have to do with how NumPy handles array scalars (https://numpy.org/doc/stable/user/basics.types.html) . Let me know if you want me to make a pull request.

**Comment by ParisNeo** [comment]
Hi. Can you fork the repo, do the updates then make a pull request ?
